### ISSUE TITLE
isExactInput is incorrectly determined

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-v3-periphery#113]
`tokenIn` and `tokenOut` are not ordered in any way, but we use the order to determine whether the swap callback is for an exact input swap
https://github.com/Uniswap/uniswap-v3-periphery/blob/2bed0d8c92d58a6c5d826a56f4c3f87f73a3dfb0/contracts/SwapRouter.sol#L66-L69

**Comment by NoahZinsmeister** [comment]
v3 core guarantees that either `amount0Delta` or `amount1Delta` will be positive, because pools need to be paid at least 1 wei for all swaps.

so, if `amount0Delta > 0`, then the swap being executed is 0 for 1, and if `amount0Delta <= 0`, then the swap being executing is 1 for 0.

so, we know that if we're in the first branch of the ternary, we're executing a 0 for 1. denoting the next 2 token elements of the path as tokenA/tokenB, we know that exact input swaps (which sort tokens in input -> output order) will have tokenA < tokenB. similarly, in the second branch of the ternary (1 for 0), exact input swaps will have tokenB < tokenA
